# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
